### ISSUE TITLE
Strange Neighbors

### ISSUE THREAD

**Issue by dc0d** [mmcloughlin/geohash#10]
Trying this package, there is strange positions for neighbors that are not where supposed to be.
![p-7](https://user-images.githubusercontent.com/3826814/40893611-b254ffcc-67b7-11e8-8180-355305b9d209.png)

**Comment by mmcloughlin** [comment]
Thanks for reporting this issue. Would you mind including the geohash you are getting neighbors for? This would help confirm my suspicion.

My current theory is that this is because of a (probably poor) decision early on for `Decode` to return `Round()` rather than `Center()` on the bounding box.

https://github.com/mmcloughlin/geohash/blob/f062401d77f5a8360a4355455806193f6301bda1/geohash.go#L124-L128

I have been debating with myself whether changing this to `Center()` would constitute a breaking change in the library. It would not violate the documented behavior of the function, but this library has enough users that there are probably people who (intentionally or otherwise) depend on the exact values it returns. See [Hyrum's Law](http://www.hyrumslaw.com/).

The conservative approach is to introduce `DecodeCenter` instead.

Thoughts appreciated.

**Comment by dc0d** [comment]
Thanks for the reply!

Starting point is `lat, lon := 35.716345, 51.423306`. And then doing this:

```go
gs := geohash.EncodeWithPrecision(lat, lon, p)
gns := geohash.Neighbors(gs)
for _, v := range gns {
	lat, lon := geohash.Decode(v)
	res = append(res, point{lat, lon})
}
```

**Comment by mmcloughlin** [comment]
Thanks for the reply. I think I have confirmed this is because of the `Round()` vs `Center()` issue I described in my previous comment. See the following gist for the code that generates this diagram.

https://gist.github.com/mmcloughlin/9ac0f6df2cf14a033facbd47dc9aa9b6

<img width="694" alt="screen shot 2018-06-04 at 7 09 33 pm" src="https://user-images.githubusercontent.com/7133685/40946352-02c840ae-682b-11e8-86ae-056878761a01.png">

Note that the blue pins are `Center()` of each neighbor, and yellow are `Round()`.

**Comment by mmcloughlin** [comment]
> Inside Neighbors() func, shouldn't it be:
> latDelta := (box.MaxLat - box.MinLat) / 2
> lngDelta := (box.MaxLng - box.MinLng) / 2

No I think it's correct as it is.

> And seems the output of BoundingBox() is not well formed - when measuring inequality of distances, one side is almost twice as the other side (some extra * 2 or / 2 somewhere?).

This is expected. Play around with the geohash explorer: http://geohash.gofreerange.com/.

**Comment by mmcloughlin** [comment]
@dc0d Does this resolve your issue? What are your thoughts on:

* Change `Decode()` to return `Center()` instead of `Round()`?
* Or, add a `DecodeCenter()` function that returns `Center()` (`Decode` stays the same)

**Comment by dc0d** [comment]
@mmcloughlin To be honest I do not understand `Round()` or it's usage - and don't like it.

And I did not expect for `Decode()` to behave this way. On the other hand people are using this library.

So if you think my assumption is logical and others might be expecting same thing, then `Decode()` must change.

If not, then `DecodeCenter()` must be added.

**Comment by mmcloughlin** [comment]
I'm annoyed with my former self for writing it this way, but I think I'd like to maintain the existing behavior since the library has a significant number of users.

Therefore I would propose `DecodeCenter()` function.

If you have time to put together the PR I would be happy to merge, otherwise leave it to me. Thanks again for posting the issue.

**Comment by dc0d** [comment]
@mmcloughlin Thanks!

No problem! But it may take some time for me to prepare the PR. So if you see fit, I leave it to you since that I am a bit short on time currently (work/diapers unbalance!).

**Comment by mmcloughlin** [comment]
Leave it to me!

**Comment by dc0d** [comment]
@mmcloughlin Seems this should get closed.
