### ISSUE TITLE
Feature request: direct conversion between int and string

### ISSUE THREAD

**Issue by ivoras** [mmcloughlin/geohash#23]
Thank you for the great work with the library!

I have a small feature request: adding functions which directly convert between the string representation and the uint64 representation (in both ways). The reason is that I'm using `uint64` internally for efficiency, but my REST APIs expose the string representation for better compatibility.

Currently I'm going through the (lat,lng) pair, e.g. with `DecodeIntWithPrecision()` and `EncodeStringWithPrecision()` but that seems inefficient and it possibly loses something in the float conversions.

**Comment by mmcloughlin** [comment]
Thank you for posting the issue. I am open to this suggestion.

The only delicate point here regards precision. A string geohash with `c` characters is just an encoding of an integer geohash with `5*c` bits of precision. How should we handle conversion of integer geohashes to strings if the precision is not a multiple of 5? Probably panic? Here's one possible API:

```go
// ConvertStringToInt converts a string geohash to the equivalent integer
// geohash. Returns the integer hash and its precision.
func ConvertStringToInt(hash string) (uint64, uint)

// ConvertIntToString converts an integer geohash with bits of precision to
// the equivalent string geohash. Requires bits to be a multiple of five, and
// will panic otherwise.
func ConvertIntToString(hash uint64, bits uint) string
```

Alternatively, you could change the signature of `ConvertIntToString` to take `chars` rather than `bits` as an argument, as follows:

```go
// ConvertIntToString converts an integer geohash to the equivalent string
// geohash with chars characters. The provided integer geohash is interpreted
// to have 5*chars bits of precision.
func ConvertIntToString(hash uint64, bits uint) string
```

These are easy to implement under the hood, I just want to make sure the API is correct. Thoughts?

**Comment by ivoras** [comment]
Excellent suggestions and reasoning, thanks!

I think the second variant of `ConvertIntToString()`, with the `chars` argument, would be cleaner. It would avoid having to check that the precision is a multiple of 5, and since the function returns a string, it seems logical to control the return value - the length of the string - in terms of characters instead of bits.

**Comment by mmcloughlin** [comment]
It would be great if you could take a quick look at #24.

**Comment by ivoras** [comment]
I've taken a look at the code and the documentation in #24, and as far as I can tell, the code and the documentation seem correct! :)

Thank you very much for the excellent work and quick replies!
