### ISSUE TITLE
any loss of precision

### ISSUE THREAD

**Issue by missinglink** [mmcloughlin/geohash#4]
hey, more of a question than an issue :)

using `EncodeInt` and encoding 2x `float64` values in to a single `uint64`, surely there is a loss of precision at some point.

i'm guessing that because Cartesian coordinates only use max 3 digits before the decimal point, that there is not too much loss of precision, although surely we can't have full `float64` precision.

how many digits of precision after the decimal point can I count on being preserved when using `EncodeInt`?

thanks!

**Comment by mmcloughlin** [comment]
Integer geohashes encode latitude and longitude with 32 bits each. Since longitude takes a larger range of values (-180 to +180), this implies longitude is encoded with less precision. In practice this means longitude is quantized to the nearest multiple of

```
360.0 / 2.0**32 = 0.0000000838190317
```

See the `encodeRange` function https://github.com/mmcloughlin/geohash/blob/525f3a7fc47c279c04049e07697970039310755d/geohash.go#L196

Therefore the encoded latitude and longitude will be less than `10^-7` away from the input. However to be pedantic, you cannot count on preservation of decimal digits as the following example shows.

```go
package main

import (
	"fmt"

	"github.com/mmcloughlin/geohash"
)

func main() {
	lat, lng := 80.0, 170.0
	fmt.Println(lat, lng)

	hash := geohash.EncodeInt(lat, lng)

	lat2, lng2 := geohash.DecodeInt(hash)
	fmt.Println(lat2, lng2)
}
```

This prints:

```
80 170
79.99999997 169.99999993
```

**Comment by missinglink** [comment]
excellent, thanks for taking the time to answer :)
